# -*- coding: utf-8 -*-
"""Copy of LerPDF.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eLZ-HasGFS1krBITiTd9EKxu_x93gQug
"""

!pip install PyPdf2

import PyPDF2

file =open('/content/BGSample-PO-0712.pdf', 'rb')
reader = PyPDF2.PdfFileReader(file)
pagina1 = reader.getPage(0)
pdfData = pagina1.extractText()

print(pdfData)

"""# New Section"""